# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from .. import _utilities, _tables

__all__ = [
    'pm_api_url',
    'pm_log_enable',
    'pm_log_file',
    'pm_log_levels',
    'pm_otp',
    'pm_parallel',
    'pm_password',
    'pm_timeout',
    'pm_tls_insecure',
    'pm_user',
]

__config__ = pulumi.Config('proxmoxve')

pm_api_url = __config__.get('pmApiUrl')
"""
https://host.fqdn:8006/api2/json
"""

pm_log_enable = __config__.get('pmLogEnable')

pm_log_file = __config__.get('pmLogFile')

pm_log_levels = __config__.get('pmLogLevels')

pm_otp = __config__.get('pmOtp')
"""
OTP 2FA code (if required)
"""

pm_parallel = __config__.get('pmParallel')

pm_password = __config__.get('pmPassword')
"""
secret
"""

pm_timeout = __config__.get('pmTimeout')

pm_tls_insecure = __config__.get('pmTlsInsecure')

pm_user = __config__.get('pmUser')
"""
username, maywith with @pam
"""

