// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("proxmoxve");

/**
 * https://host.fqdn:8006/api2/json
 */
export let pmApiUrl: string | undefined = __config.get("pmApiUrl");
/**
 * By default this provider will exit if an unknown attribute is found. This is to prevent the accidential destruction of
 * VMs or Data when something in the proxmox API has changed/updated and is not confirmed to work with this provider. Set
 * this to true at your own risk. It may allow you to proceed in cases when the provider refuses to work, but be aware of
 * the danger in doing so.
 */
export let pmDangerouslyIgnoreUnknownAttributes: boolean | undefined = __config.getObject<boolean>("pmDangerouslyIgnoreUnknownAttributes");
export let pmLogEnable: boolean | undefined = __config.getObject<boolean>("pmLogEnable");
export let pmLogFile: string | undefined = __config.get("pmLogFile");
export let pmLogLevels: {[key: string]: any} | undefined = __config.getObject<{[key: string]: any}>("pmLogLevels");
/**
 * OTP 2FA code (if required)
 */
export let pmOtp: string | undefined = __config.get("pmOtp");
export let pmParallel: number | undefined = __config.getObject<number>("pmParallel");
/**
 * secret
 */
export let pmPassword: string | undefined = __config.get("pmPassword");
export let pmTimeout: number | undefined = __config.getObject<number>("pmTimeout");
export let pmTlsInsecure: boolean | undefined = __config.getObject<boolean>("pmTlsInsecure");
/**
 * username, maywith with @pam
 */
export let pmUser: string | undefined = __config.get("pmUser");
