// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmoxve.Outputs
{

    [OutputType]
    public sealed class Lxc_containerMountpoint
    {
        public readonly bool? Acl;
        public readonly bool? Backup;
        public readonly string Mp;
        public readonly bool? Quota;
        public readonly bool? Replicate;
        public readonly bool? Shared;
        public readonly int? Size;
        public readonly string Volume;

        [OutputConstructor]
        private Lxc_containerMountpoint(
            bool? acl,

            bool? backup,

            string mp,

            bool? quota,

            bool? replicate,

            bool? shared,

            int? size,

            string volume)
        {
            Acl = acl;
            Backup = backup;
            Mp = mp;
            Quota = quota;
            Replicate = replicate;
            Shared = shared;
            Size = size;
            Volume = volume;
        }
    }
}
