// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmoxve.Outputs
{

    [OutputType]
    public sealed class LXCContainerFeature
    {
        public readonly bool? Fuse;
        public readonly bool? Keyctl;
        public readonly string? Mount;
        public readonly bool? Nesting;

        [OutputConstructor]
        private LXCContainerFeature(
            bool? fuse,

            bool? keyctl,

            string? mount,

            bool? nesting)
        {
            Fuse = fuse;
            Keyctl = keyctl;
            Mount = mount;
            Nesting = nesting;
        }
    }
}
