// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface Lxc_containerFeature {
    fuse?: pulumi.Input<boolean>;
    keyctl?: pulumi.Input<boolean>;
    mount?: pulumi.Input<string>;
    nesting?: pulumi.Input<boolean>;
}

export interface Lxc_containerMountpoint {
    acl?: pulumi.Input<boolean>;
    backup?: pulumi.Input<boolean>;
    mp: pulumi.Input<string>;
    quota?: pulumi.Input<boolean>;
    replicate?: pulumi.Input<boolean>;
    shared?: pulumi.Input<boolean>;
    size?: pulumi.Input<number>;
    volume: pulumi.Input<string>;
}

export interface Lxc_containerNetwork {
    bridge?: pulumi.Input<string>;
    firewall?: pulumi.Input<boolean>;
    gw?: pulumi.Input<string>;
    gw6?: pulumi.Input<string>;
    hwaddr?: pulumi.Input<string>;
    ip?: pulumi.Input<string>;
    ip6?: pulumi.Input<string>;
    mtu?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    rate?: pulumi.Input<number>;
    tag?: pulumi.Input<number>;
    trunks?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
}

export interface Qemu_vmDisk {
    backup?: pulumi.Input<boolean>;
    cache?: pulumi.Input<string>;
    discard?: pulumi.Input<string>;
    file?: pulumi.Input<string>;
    format?: pulumi.Input<string>;
    iothread?: pulumi.Input<boolean>;
    mbps?: pulumi.Input<number>;
    mbpsRd?: pulumi.Input<number>;
    mbpsRdMax?: pulumi.Input<number>;
    mbpsWr?: pulumi.Input<number>;
    mbpsWrMax?: pulumi.Input<number>;
    media?: pulumi.Input<string>;
    replicate?: pulumi.Input<boolean>;
    size: pulumi.Input<string>;
    ssd?: pulumi.Input<boolean>;
    storage: pulumi.Input<string>;
    storageType?: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface Qemu_vmNetwork {
    bridge?: pulumi.Input<string>;
    firewall?: pulumi.Input<boolean>;
    linkDown?: pulumi.Input<boolean>;
    macaddr?: pulumi.Input<string>;
    model: pulumi.Input<string>;
    queues?: pulumi.Input<number>;
    rate?: pulumi.Input<number>;
    tag?: pulumi.Input<number>;
}

export interface Qemu_vmSerial {
    id: pulumi.Input<number>;
    type: pulumi.Input<string>;
}

export interface Qemu_vmVga {
    memory?: pulumi.Input<number>;
    type?: pulumi.Input<string>;
}
