// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmoxve.Inputs
{

    public sealed class LXCContainerNetworkArgs : Pulumi.ResourceArgs
    {
        [Input("bridge")]
        public Input<string>? Bridge { get; set; }

        [Input("firewall")]
        public Input<bool>? Firewall { get; set; }

        [Input("gw")]
        public Input<string>? Gw { get; set; }

        [Input("gw6")]
        public Input<string>? Gw6 { get; set; }

        [Input("hwaddr")]
        public Input<string>? Hwaddr { get; set; }

        [Input("ip")]
        public Input<string>? Ip { get; set; }

        [Input("ip6")]
        public Input<string>? Ip6 { get; set; }

        [Input("mtu")]
        public Input<string>? Mtu { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("rate")]
        public Input<int>? Rate { get; set; }

        [Input("tag")]
        public Input<int>? Tag { get; set; }

        [Input("trunks")]
        public Input<string>? Trunks { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public LXCContainerNetworkArgs()
        {
        }
    }
}
