// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmoxve.Inputs
{

    public sealed class QemuVMUnusedDiskGetArgs : Pulumi.ResourceArgs
    {
        [Input("file")]
        public Input<string>? File { get; set; }

        [Input("slot")]
        public Input<int>? Slot { get; set; }

        [Input("storage")]
        public Input<string>? Storage { get; set; }

        public QemuVMUnusedDiskGetArgs()
        {
        }
    }
}
