// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmoxve.Inputs
{

    public sealed class QemuVMNetworkArgs : Pulumi.ResourceArgs
    {
        [Input("bridge")]
        public Input<string>? Bridge { get; set; }

        [Input("firewall")]
        public Input<bool>? Firewall { get; set; }

        [Input("linkDown")]
        public Input<bool>? LinkDown { get; set; }

        [Input("macaddr")]
        public Input<string>? Macaddr { get; set; }

        [Input("model", required: true)]
        public Input<string> Model { get; set; } = null!;

        [Input("queues")]
        public Input<int>? Queues { get; set; }

        [Input("rate")]
        public Input<int>? Rate { get; set; }

        [Input("tag")]
        public Input<int>? Tag { get; set; }

        public QemuVMNetworkArgs()
        {
        }
    }
}
