// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package proxmoxve

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type LXCContainer struct {
	pulumi.CustomResourceState

	Arch               pulumi.StringPtrOutput            `pulumi:"arch"`
	Bwlimit            pulumi.IntPtrOutput               `pulumi:"bwlimit"`
	Cmode              pulumi.StringPtrOutput            `pulumi:"cmode"`
	Console            pulumi.BoolPtrOutput              `pulumi:"console"`
	Cores              pulumi.IntPtrOutput               `pulumi:"cores"`
	Cpulimit           pulumi.IntPtrOutput               `pulumi:"cpulimit"`
	Cpuunits           pulumi.IntPtrOutput               `pulumi:"cpuunits"`
	Description        pulumi.StringPtrOutput            `pulumi:"description"`
	Features           LXCContainerFeaturesPtrOutput     `pulumi:"features"`
	Force              pulumi.BoolPtrOutput              `pulumi:"force"`
	Hookscript         pulumi.StringPtrOutput            `pulumi:"hookscript"`
	Hostname           pulumi.StringPtrOutput            `pulumi:"hostname"`
	IgnoreUnpackErrors pulumi.BoolPtrOutput              `pulumi:"ignoreUnpackErrors"`
	Lock               pulumi.StringPtrOutput            `pulumi:"lock"`
	Memory             pulumi.IntPtrOutput               `pulumi:"memory"`
	Mountpoints        LXCContainerMountpointArrayOutput `pulumi:"mountpoints"`
	Nameserver         pulumi.StringPtrOutput            `pulumi:"nameserver"`
	Networks           LXCContainerNetworkArrayOutput    `pulumi:"networks"`
	Onboot             pulumi.BoolPtrOutput              `pulumi:"onboot"`
	Ostemplate         pulumi.StringPtrOutput            `pulumi:"ostemplate"`
	Ostype             pulumi.StringOutput               `pulumi:"ostype"`
	Password           pulumi.StringPtrOutput            `pulumi:"password"`
	Pool               pulumi.StringPtrOutput            `pulumi:"pool"`
	Protection         pulumi.BoolPtrOutput              `pulumi:"protection"`
	Restore            pulumi.BoolPtrOutput              `pulumi:"restore"`
	Rootfs             LXCContainerRootfsPtrOutput       `pulumi:"rootfs"`
	Searchdomain       pulumi.StringPtrOutput            `pulumi:"searchdomain"`
	SshPublicKeys      pulumi.StringPtrOutput            `pulumi:"sshPublicKeys"`
	Start              pulumi.BoolPtrOutput              `pulumi:"start"`
	Startup            pulumi.StringPtrOutput            `pulumi:"startup"`
	Swap               pulumi.IntPtrOutput               `pulumi:"swap"`
	Tags               pulumi.StringPtrOutput            `pulumi:"tags"`
	TargetNode         pulumi.StringOutput               `pulumi:"targetNode"`
	Template           pulumi.BoolPtrOutput              `pulumi:"template"`
	Tty                pulumi.IntPtrOutput               `pulumi:"tty"`
	Unique             pulumi.BoolPtrOutput              `pulumi:"unique"`
	Unprivileged       pulumi.BoolPtrOutput              `pulumi:"unprivileged"`
	Unuseds            pulumi.StringArrayOutput          `pulumi:"unuseds"`
	Vmid               pulumi.IntPtrOutput               `pulumi:"vmid"`
}

// NewLXCContainer registers a new resource with the given unique name, arguments, and options.
func NewLXCContainer(ctx *pulumi.Context,
	name string, args *LXCContainerArgs, opts ...pulumi.ResourceOption) (*LXCContainer, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.TargetNode == nil {
		return nil, errors.New("invalid value for required argument 'TargetNode'")
	}
	var resource LXCContainer
	err := ctx.RegisterResource("proxmoxve:index/lXCContainer:LXCContainer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLXCContainer gets an existing LXCContainer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLXCContainer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LXCContainerState, opts ...pulumi.ResourceOption) (*LXCContainer, error) {
	var resource LXCContainer
	err := ctx.ReadResource("proxmoxve:index/lXCContainer:LXCContainer", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LXCContainer resources.
type lxccontainerState struct {
	Arch               *string                  `pulumi:"arch"`
	Bwlimit            *int                     `pulumi:"bwlimit"`
	Cmode              *string                  `pulumi:"cmode"`
	Console            *bool                    `pulumi:"console"`
	Cores              *int                     `pulumi:"cores"`
	Cpulimit           *int                     `pulumi:"cpulimit"`
	Cpuunits           *int                     `pulumi:"cpuunits"`
	Description        *string                  `pulumi:"description"`
	Features           *LXCContainerFeatures    `pulumi:"features"`
	Force              *bool                    `pulumi:"force"`
	Hookscript         *string                  `pulumi:"hookscript"`
	Hostname           *string                  `pulumi:"hostname"`
	IgnoreUnpackErrors *bool                    `pulumi:"ignoreUnpackErrors"`
	Lock               *string                  `pulumi:"lock"`
	Memory             *int                     `pulumi:"memory"`
	Mountpoints        []LXCContainerMountpoint `pulumi:"mountpoints"`
	Nameserver         *string                  `pulumi:"nameserver"`
	Networks           []LXCContainerNetwork    `pulumi:"networks"`
	Onboot             *bool                    `pulumi:"onboot"`
	Ostemplate         *string                  `pulumi:"ostemplate"`
	Ostype             *string                  `pulumi:"ostype"`
	Password           *string                  `pulumi:"password"`
	Pool               *string                  `pulumi:"pool"`
	Protection         *bool                    `pulumi:"protection"`
	Restore            *bool                    `pulumi:"restore"`
	Rootfs             *LXCContainerRootfs      `pulumi:"rootfs"`
	Searchdomain       *string                  `pulumi:"searchdomain"`
	SshPublicKeys      *string                  `pulumi:"sshPublicKeys"`
	Start              *bool                    `pulumi:"start"`
	Startup            *string                  `pulumi:"startup"`
	Swap               *int                     `pulumi:"swap"`
	Tags               *string                  `pulumi:"tags"`
	TargetNode         *string                  `pulumi:"targetNode"`
	Template           *bool                    `pulumi:"template"`
	Tty                *int                     `pulumi:"tty"`
	Unique             *bool                    `pulumi:"unique"`
	Unprivileged       *bool                    `pulumi:"unprivileged"`
	Unuseds            []string                 `pulumi:"unuseds"`
	Vmid               *int                     `pulumi:"vmid"`
}

type LXCContainerState struct {
	Arch               pulumi.StringPtrInput
	Bwlimit            pulumi.IntPtrInput
	Cmode              pulumi.StringPtrInput
	Console            pulumi.BoolPtrInput
	Cores              pulumi.IntPtrInput
	Cpulimit           pulumi.IntPtrInput
	Cpuunits           pulumi.IntPtrInput
	Description        pulumi.StringPtrInput
	Features           LXCContainerFeaturesPtrInput
	Force              pulumi.BoolPtrInput
	Hookscript         pulumi.StringPtrInput
	Hostname           pulumi.StringPtrInput
	IgnoreUnpackErrors pulumi.BoolPtrInput
	Lock               pulumi.StringPtrInput
	Memory             pulumi.IntPtrInput
	Mountpoints        LXCContainerMountpointArrayInput
	Nameserver         pulumi.StringPtrInput
	Networks           LXCContainerNetworkArrayInput
	Onboot             pulumi.BoolPtrInput
	Ostemplate         pulumi.StringPtrInput
	Ostype             pulumi.StringPtrInput
	Password           pulumi.StringPtrInput
	Pool               pulumi.StringPtrInput
	Protection         pulumi.BoolPtrInput
	Restore            pulumi.BoolPtrInput
	Rootfs             LXCContainerRootfsPtrInput
	Searchdomain       pulumi.StringPtrInput
	SshPublicKeys      pulumi.StringPtrInput
	Start              pulumi.BoolPtrInput
	Startup            pulumi.StringPtrInput
	Swap               pulumi.IntPtrInput
	Tags               pulumi.StringPtrInput
	TargetNode         pulumi.StringPtrInput
	Template           pulumi.BoolPtrInput
	Tty                pulumi.IntPtrInput
	Unique             pulumi.BoolPtrInput
	Unprivileged       pulumi.BoolPtrInput
	Unuseds            pulumi.StringArrayInput
	Vmid               pulumi.IntPtrInput
}

func (LXCContainerState) ElementType() reflect.Type {
	return reflect.TypeOf((*lxccontainerState)(nil)).Elem()
}

type lxccontainerArgs struct {
	Arch               *string                  `pulumi:"arch"`
	Bwlimit            *int                     `pulumi:"bwlimit"`
	Cmode              *string                  `pulumi:"cmode"`
	Console            *bool                    `pulumi:"console"`
	Cores              *int                     `pulumi:"cores"`
	Cpulimit           *int                     `pulumi:"cpulimit"`
	Cpuunits           *int                     `pulumi:"cpuunits"`
	Description        *string                  `pulumi:"description"`
	Features           *LXCContainerFeatures    `pulumi:"features"`
	Force              *bool                    `pulumi:"force"`
	Hookscript         *string                  `pulumi:"hookscript"`
	Hostname           *string                  `pulumi:"hostname"`
	IgnoreUnpackErrors *bool                    `pulumi:"ignoreUnpackErrors"`
	Lock               *string                  `pulumi:"lock"`
	Memory             *int                     `pulumi:"memory"`
	Mountpoints        []LXCContainerMountpoint `pulumi:"mountpoints"`
	Nameserver         *string                  `pulumi:"nameserver"`
	Networks           []LXCContainerNetwork    `pulumi:"networks"`
	Onboot             *bool                    `pulumi:"onboot"`
	Ostemplate         *string                  `pulumi:"ostemplate"`
	Ostype             *string                  `pulumi:"ostype"`
	Password           *string                  `pulumi:"password"`
	Pool               *string                  `pulumi:"pool"`
	Protection         *bool                    `pulumi:"protection"`
	Restore            *bool                    `pulumi:"restore"`
	Rootfs             *LXCContainerRootfs      `pulumi:"rootfs"`
	Searchdomain       *string                  `pulumi:"searchdomain"`
	SshPublicKeys      *string                  `pulumi:"sshPublicKeys"`
	Start              *bool                    `pulumi:"start"`
	Startup            *string                  `pulumi:"startup"`
	Swap               *int                     `pulumi:"swap"`
	Tags               *string                  `pulumi:"tags"`
	TargetNode         string                   `pulumi:"targetNode"`
	Template           *bool                    `pulumi:"template"`
	Tty                *int                     `pulumi:"tty"`
	Unique             *bool                    `pulumi:"unique"`
	Unprivileged       *bool                    `pulumi:"unprivileged"`
	Unuseds            []string                 `pulumi:"unuseds"`
	Vmid               *int                     `pulumi:"vmid"`
}

// The set of arguments for constructing a LXCContainer resource.
type LXCContainerArgs struct {
	Arch               pulumi.StringPtrInput
	Bwlimit            pulumi.IntPtrInput
	Cmode              pulumi.StringPtrInput
	Console            pulumi.BoolPtrInput
	Cores              pulumi.IntPtrInput
	Cpulimit           pulumi.IntPtrInput
	Cpuunits           pulumi.IntPtrInput
	Description        pulumi.StringPtrInput
	Features           LXCContainerFeaturesPtrInput
	Force              pulumi.BoolPtrInput
	Hookscript         pulumi.StringPtrInput
	Hostname           pulumi.StringPtrInput
	IgnoreUnpackErrors pulumi.BoolPtrInput
	Lock               pulumi.StringPtrInput
	Memory             pulumi.IntPtrInput
	Mountpoints        LXCContainerMountpointArrayInput
	Nameserver         pulumi.StringPtrInput
	Networks           LXCContainerNetworkArrayInput
	Onboot             pulumi.BoolPtrInput
	Ostemplate         pulumi.StringPtrInput
	Ostype             pulumi.StringPtrInput
	Password           pulumi.StringPtrInput
	Pool               pulumi.StringPtrInput
	Protection         pulumi.BoolPtrInput
	Restore            pulumi.BoolPtrInput
	Rootfs             LXCContainerRootfsPtrInput
	Searchdomain       pulumi.StringPtrInput
	SshPublicKeys      pulumi.StringPtrInput
	Start              pulumi.BoolPtrInput
	Startup            pulumi.StringPtrInput
	Swap               pulumi.IntPtrInput
	Tags               pulumi.StringPtrInput
	TargetNode         pulumi.StringInput
	Template           pulumi.BoolPtrInput
	Tty                pulumi.IntPtrInput
	Unique             pulumi.BoolPtrInput
	Unprivileged       pulumi.BoolPtrInput
	Unuseds            pulumi.StringArrayInput
	Vmid               pulumi.IntPtrInput
}

func (LXCContainerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lxccontainerArgs)(nil)).Elem()
}

type LXCContainerInput interface {
	pulumi.Input

	ToLXCContainerOutput() LXCContainerOutput
	ToLXCContainerOutputWithContext(ctx context.Context) LXCContainerOutput
}

func (*LXCContainer) ElementType() reflect.Type {
	return reflect.TypeOf((*LXCContainer)(nil))
}

func (i *LXCContainer) ToLXCContainerOutput() LXCContainerOutput {
	return i.ToLXCContainerOutputWithContext(context.Background())
}

func (i *LXCContainer) ToLXCContainerOutputWithContext(ctx context.Context) LXCContainerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LXCContainerOutput)
}

func (i *LXCContainer) ToLXCContainerPtrOutput() LXCContainerPtrOutput {
	return i.ToLXCContainerPtrOutputWithContext(context.Background())
}

func (i *LXCContainer) ToLXCContainerPtrOutputWithContext(ctx context.Context) LXCContainerPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LXCContainerPtrOutput)
}

type LXCContainerPtrInput interface {
	pulumi.Input

	ToLXCContainerPtrOutput() LXCContainerPtrOutput
	ToLXCContainerPtrOutputWithContext(ctx context.Context) LXCContainerPtrOutput
}

type lxccontainerPtrType LXCContainerArgs

func (*lxccontainerPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**LXCContainer)(nil))
}

func (i *lxccontainerPtrType) ToLXCContainerPtrOutput() LXCContainerPtrOutput {
	return i.ToLXCContainerPtrOutputWithContext(context.Background())
}

func (i *lxccontainerPtrType) ToLXCContainerPtrOutputWithContext(ctx context.Context) LXCContainerPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LXCContainerPtrOutput)
}

// LXCContainerArrayInput is an input type that accepts LXCContainerArray and LXCContainerArrayOutput values.
// You can construct a concrete instance of `LXCContainerArrayInput` via:
//
//          LXCContainerArray{ LXCContainerArgs{...} }
type LXCContainerArrayInput interface {
	pulumi.Input

	ToLXCContainerArrayOutput() LXCContainerArrayOutput
	ToLXCContainerArrayOutputWithContext(context.Context) LXCContainerArrayOutput
}

type LXCContainerArray []LXCContainerInput

func (LXCContainerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LXCContainer)(nil)).Elem()
}

func (i LXCContainerArray) ToLXCContainerArrayOutput() LXCContainerArrayOutput {
	return i.ToLXCContainerArrayOutputWithContext(context.Background())
}

func (i LXCContainerArray) ToLXCContainerArrayOutputWithContext(ctx context.Context) LXCContainerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LXCContainerArrayOutput)
}

// LXCContainerMapInput is an input type that accepts LXCContainerMap and LXCContainerMapOutput values.
// You can construct a concrete instance of `LXCContainerMapInput` via:
//
//          LXCContainerMap{ "key": LXCContainerArgs{...} }
type LXCContainerMapInput interface {
	pulumi.Input

	ToLXCContainerMapOutput() LXCContainerMapOutput
	ToLXCContainerMapOutputWithContext(context.Context) LXCContainerMapOutput
}

type LXCContainerMap map[string]LXCContainerInput

func (LXCContainerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LXCContainer)(nil)).Elem()
}

func (i LXCContainerMap) ToLXCContainerMapOutput() LXCContainerMapOutput {
	return i.ToLXCContainerMapOutputWithContext(context.Background())
}

func (i LXCContainerMap) ToLXCContainerMapOutputWithContext(ctx context.Context) LXCContainerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LXCContainerMapOutput)
}

type LXCContainerOutput struct{ *pulumi.OutputState }

func (LXCContainerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LXCContainer)(nil))
}

func (o LXCContainerOutput) ToLXCContainerOutput() LXCContainerOutput {
	return o
}

func (o LXCContainerOutput) ToLXCContainerOutputWithContext(ctx context.Context) LXCContainerOutput {
	return o
}

func (o LXCContainerOutput) ToLXCContainerPtrOutput() LXCContainerPtrOutput {
	return o.ToLXCContainerPtrOutputWithContext(context.Background())
}

func (o LXCContainerOutput) ToLXCContainerPtrOutputWithContext(ctx context.Context) LXCContainerPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v LXCContainer) *LXCContainer {
		return &v
	}).(LXCContainerPtrOutput)
}

type LXCContainerPtrOutput struct{ *pulumi.OutputState }

func (LXCContainerPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LXCContainer)(nil))
}

func (o LXCContainerPtrOutput) ToLXCContainerPtrOutput() LXCContainerPtrOutput {
	return o
}

func (o LXCContainerPtrOutput) ToLXCContainerPtrOutputWithContext(ctx context.Context) LXCContainerPtrOutput {
	return o
}

func (o LXCContainerPtrOutput) Elem() LXCContainerOutput {
	return o.ApplyT(func(v *LXCContainer) LXCContainer {
		if v != nil {
			return *v
		}
		var ret LXCContainer
		return ret
	}).(LXCContainerOutput)
}

type LXCContainerArrayOutput struct{ *pulumi.OutputState }

func (LXCContainerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LXCContainer)(nil))
}

func (o LXCContainerArrayOutput) ToLXCContainerArrayOutput() LXCContainerArrayOutput {
	return o
}

func (o LXCContainerArrayOutput) ToLXCContainerArrayOutputWithContext(ctx context.Context) LXCContainerArrayOutput {
	return o
}

func (o LXCContainerArrayOutput) Index(i pulumi.IntInput) LXCContainerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) LXCContainer {
		return vs[0].([]LXCContainer)[vs[1].(int)]
	}).(LXCContainerOutput)
}

type LXCContainerMapOutput struct{ *pulumi.OutputState }

func (LXCContainerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]LXCContainer)(nil))
}

func (o LXCContainerMapOutput) ToLXCContainerMapOutput() LXCContainerMapOutput {
	return o
}

func (o LXCContainerMapOutput) ToLXCContainerMapOutputWithContext(ctx context.Context) LXCContainerMapOutput {
	return o
}

func (o LXCContainerMapOutput) MapIndex(k pulumi.StringInput) LXCContainerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) LXCContainer {
		return vs[0].(map[string]LXCContainer)[vs[1].(string)]
	}).(LXCContainerOutput)
}

func init() {
	pulumi.RegisterOutputType(LXCContainerOutput{})
	pulumi.RegisterOutputType(LXCContainerPtrOutput{})
	pulumi.RegisterOutputType(LXCContainerArrayOutput{})
	pulumi.RegisterOutputType(LXCContainerMapOutput{})
}
