// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package proxmoxve

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type QemuVM struct {
	pulumi.CustomResourceState

	Agent    pulumi.IntPtrOutput    `pulumi:"agent"`
	Balloon  pulumi.IntPtrOutput    `pulumi:"balloon"`
	Bios     pulumi.StringPtrOutput `pulumi:"bios"`
	Boot     pulumi.StringPtrOutput `pulumi:"boot"`
	Bootdisk pulumi.StringOutput    `pulumi:"bootdisk"`
	// Deprecated: Use `network.bridge` instead
	Bridge               pulumi.StringPtrOutput `pulumi:"bridge"`
	CiWait               pulumi.IntPtrOutput    `pulumi:"ciWait"`
	Cicustom             pulumi.StringPtrOutput `pulumi:"cicustom"`
	Cipassword           pulumi.StringPtrOutput `pulumi:"cipassword"`
	Ciuser               pulumi.StringPtrOutput `pulumi:"ciuser"`
	Clone                pulumi.StringPtrOutput `pulumi:"clone"`
	CloneWait            pulumi.IntPtrOutput    `pulumi:"cloneWait"`
	Cores                pulumi.IntPtrOutput    `pulumi:"cores"`
	Cpu                  pulumi.StringPtrOutput `pulumi:"cpu"`
	DefineConnectionInfo pulumi.BoolPtrOutput   `pulumi:"defineConnectionInfo"`
	Desc                 pulumi.StringPtrOutput `pulumi:"desc"`
	// Deprecated: Use `disk.size` instead
	DiskGb                  pulumi.Float64PtrOutput `pulumi:"diskGb"`
	Disks                   QemuVMDiskArrayOutput   `pulumi:"disks"`
	ForceCreate             pulumi.BoolPtrOutput    `pulumi:"forceCreate"`
	ForceRecreateOnChangeOf pulumi.StringPtrOutput  `pulumi:"forceRecreateOnChangeOf"`
	FullClone               pulumi.BoolPtrOutput    `pulumi:"fullClone"`
	Hastate                 pulumi.StringPtrOutput  `pulumi:"hastate"`
	Hotplug                 pulumi.StringPtrOutput  `pulumi:"hotplug"`
	Ipconfig0               pulumi.StringPtrOutput  `pulumi:"ipconfig0"`
	Ipconfig1               pulumi.StringPtrOutput  `pulumi:"ipconfig1"`
	Ipconfig2               pulumi.StringPtrOutput  `pulumi:"ipconfig2"`
	Iso                     pulumi.StringPtrOutput  `pulumi:"iso"`
	Kvm                     pulumi.BoolPtrOutput    `pulumi:"kvm"`
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac        pulumi.StringPtrOutput   `pulumi:"mac"`
	Memory     pulumi.IntPtrOutput      `pulumi:"memory"`
	Name       pulumi.StringOutput      `pulumi:"name"`
	Nameserver pulumi.StringOutput      `pulumi:"nameserver"`
	Networks   QemuVMNetworkArrayOutput `pulumi:"networks"`
	// Deprecated: Use `network` instead
	Nic             pulumi.StringPtrOutput  `pulumi:"nic"`
	Numa            pulumi.BoolPtrOutput    `pulumi:"numa"`
	Onboot          pulumi.BoolPtrOutput    `pulumi:"onboot"`
	OsNetworkConfig pulumi.StringPtrOutput  `pulumi:"osNetworkConfig"`
	OsType          pulumi.StringPtrOutput  `pulumi:"osType"`
	Pool            pulumi.StringPtrOutput  `pulumi:"pool"`
	Preprovision    pulumi.BoolPtrOutput    `pulumi:"preprovision"`
	QemuOs          pulumi.StringPtrOutput  `pulumi:"qemuOs"`
	Scsihw          pulumi.StringOutput     `pulumi:"scsihw"`
	Searchdomain    pulumi.StringOutput     `pulumi:"searchdomain"`
	Serials         QemuVMSerialArrayOutput `pulumi:"serials"`
	Sockets         pulumi.IntPtrOutput     `pulumi:"sockets"`
	SshForwardIp    pulumi.StringPtrOutput  `pulumi:"sshForwardIp"`
	SshHost         pulumi.StringOutput     `pulumi:"sshHost"`
	SshPort         pulumi.StringOutput     `pulumi:"sshPort"`
	SshPrivateKey   pulumi.StringPtrOutput  `pulumi:"sshPrivateKey"`
	SshUser         pulumi.StringPtrOutput  `pulumi:"sshUser"`
	Sshkeys         pulumi.StringPtrOutput  `pulumi:"sshkeys"`
	// Deprecated: Use `disk.storage` instead
	Storage pulumi.StringPtrOutput `pulumi:"storage"`
	// Deprecated: Use `disk.type` instead
	StorageType pulumi.StringPtrOutput `pulumi:"storageType"`
	TargetNode  pulumi.StringOutput    `pulumi:"targetNode"`
	Vcpus       pulumi.IntPtrOutput    `pulumi:"vcpus"`
	Vgas        QemuVMVgaArrayOutput   `pulumi:"vgas"`
	// Deprecated: Use `network.tag` instead
	Vlan pulumi.IntPtrOutput `pulumi:"vlan"`
	Vmid pulumi.IntOutput    `pulumi:"vmid"`
}

// NewQemuVM registers a new resource with the given unique name, arguments, and options.
func NewQemuVM(ctx *pulumi.Context,
	name string, args *QemuVMArgs, opts ...pulumi.ResourceOption) (*QemuVM, error) {
	if args == nil || args.TargetNode == nil {
		return nil, errors.New("missing required argument 'TargetNode'")
	}
	if args == nil {
		args = &QemuVMArgs{}
	}
	var resource QemuVM
	err := ctx.RegisterResource("proxmoxve:index/qemuVM:QemuVM", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetQemuVM gets an existing QemuVM resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetQemuVM(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *QemuVMState, opts ...pulumi.ResourceOption) (*QemuVM, error) {
	var resource QemuVM
	err := ctx.ReadResource("proxmoxve:index/qemuVM:QemuVM", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering QemuVM resources.
type qemuVMState struct {
	Agent    *int    `pulumi:"agent"`
	Balloon  *int    `pulumi:"balloon"`
	Bios     *string `pulumi:"bios"`
	Boot     *string `pulumi:"boot"`
	Bootdisk *string `pulumi:"bootdisk"`
	// Deprecated: Use `network.bridge` instead
	Bridge               *string `pulumi:"bridge"`
	CiWait               *int    `pulumi:"ciWait"`
	Cicustom             *string `pulumi:"cicustom"`
	Cipassword           *string `pulumi:"cipassword"`
	Ciuser               *string `pulumi:"ciuser"`
	Clone                *string `pulumi:"clone"`
	CloneWait            *int    `pulumi:"cloneWait"`
	Cores                *int    `pulumi:"cores"`
	Cpu                  *string `pulumi:"cpu"`
	DefineConnectionInfo *bool   `pulumi:"defineConnectionInfo"`
	Desc                 *string `pulumi:"desc"`
	// Deprecated: Use `disk.size` instead
	DiskGb                  *float64     `pulumi:"diskGb"`
	Disks                   []QemuVMDisk `pulumi:"disks"`
	ForceCreate             *bool        `pulumi:"forceCreate"`
	ForceRecreateOnChangeOf *string      `pulumi:"forceRecreateOnChangeOf"`
	FullClone               *bool        `pulumi:"fullClone"`
	Hastate                 *string      `pulumi:"hastate"`
	Hotplug                 *string      `pulumi:"hotplug"`
	Ipconfig0               *string      `pulumi:"ipconfig0"`
	Ipconfig1               *string      `pulumi:"ipconfig1"`
	Ipconfig2               *string      `pulumi:"ipconfig2"`
	Iso                     *string      `pulumi:"iso"`
	Kvm                     *bool        `pulumi:"kvm"`
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac        *string         `pulumi:"mac"`
	Memory     *int            `pulumi:"memory"`
	Name       *string         `pulumi:"name"`
	Nameserver *string         `pulumi:"nameserver"`
	Networks   []QemuVMNetwork `pulumi:"networks"`
	// Deprecated: Use `network` instead
	Nic             *string        `pulumi:"nic"`
	Numa            *bool          `pulumi:"numa"`
	Onboot          *bool          `pulumi:"onboot"`
	OsNetworkConfig *string        `pulumi:"osNetworkConfig"`
	OsType          *string        `pulumi:"osType"`
	Pool            *string        `pulumi:"pool"`
	Preprovision    *bool          `pulumi:"preprovision"`
	QemuOs          *string        `pulumi:"qemuOs"`
	Scsihw          *string        `pulumi:"scsihw"`
	Searchdomain    *string        `pulumi:"searchdomain"`
	Serials         []QemuVMSerial `pulumi:"serials"`
	Sockets         *int           `pulumi:"sockets"`
	SshForwardIp    *string        `pulumi:"sshForwardIp"`
	SshHost         *string        `pulumi:"sshHost"`
	SshPort         *string        `pulumi:"sshPort"`
	SshPrivateKey   *string        `pulumi:"sshPrivateKey"`
	SshUser         *string        `pulumi:"sshUser"`
	Sshkeys         *string        `pulumi:"sshkeys"`
	// Deprecated: Use `disk.storage` instead
	Storage *string `pulumi:"storage"`
	// Deprecated: Use `disk.type` instead
	StorageType *string     `pulumi:"storageType"`
	TargetNode  *string     `pulumi:"targetNode"`
	Vcpus       *int        `pulumi:"vcpus"`
	Vgas        []QemuVMVga `pulumi:"vgas"`
	// Deprecated: Use `network.tag` instead
	Vlan *int `pulumi:"vlan"`
	Vmid *int `pulumi:"vmid"`
}

type QemuVMState struct {
	Agent    pulumi.IntPtrInput
	Balloon  pulumi.IntPtrInput
	Bios     pulumi.StringPtrInput
	Boot     pulumi.StringPtrInput
	Bootdisk pulumi.StringPtrInput
	// Deprecated: Use `network.bridge` instead
	Bridge               pulumi.StringPtrInput
	CiWait               pulumi.IntPtrInput
	Cicustom             pulumi.StringPtrInput
	Cipassword           pulumi.StringPtrInput
	Ciuser               pulumi.StringPtrInput
	Clone                pulumi.StringPtrInput
	CloneWait            pulumi.IntPtrInput
	Cores                pulumi.IntPtrInput
	Cpu                  pulumi.StringPtrInput
	DefineConnectionInfo pulumi.BoolPtrInput
	Desc                 pulumi.StringPtrInput
	// Deprecated: Use `disk.size` instead
	DiskGb                  pulumi.Float64PtrInput
	Disks                   QemuVMDiskArrayInput
	ForceCreate             pulumi.BoolPtrInput
	ForceRecreateOnChangeOf pulumi.StringPtrInput
	FullClone               pulumi.BoolPtrInput
	Hastate                 pulumi.StringPtrInput
	Hotplug                 pulumi.StringPtrInput
	Ipconfig0               pulumi.StringPtrInput
	Ipconfig1               pulumi.StringPtrInput
	Ipconfig2               pulumi.StringPtrInput
	Iso                     pulumi.StringPtrInput
	Kvm                     pulumi.BoolPtrInput
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac        pulumi.StringPtrInput
	Memory     pulumi.IntPtrInput
	Name       pulumi.StringPtrInput
	Nameserver pulumi.StringPtrInput
	Networks   QemuVMNetworkArrayInput
	// Deprecated: Use `network` instead
	Nic             pulumi.StringPtrInput
	Numa            pulumi.BoolPtrInput
	Onboot          pulumi.BoolPtrInput
	OsNetworkConfig pulumi.StringPtrInput
	OsType          pulumi.StringPtrInput
	Pool            pulumi.StringPtrInput
	Preprovision    pulumi.BoolPtrInput
	QemuOs          pulumi.StringPtrInput
	Scsihw          pulumi.StringPtrInput
	Searchdomain    pulumi.StringPtrInput
	Serials         QemuVMSerialArrayInput
	Sockets         pulumi.IntPtrInput
	SshForwardIp    pulumi.StringPtrInput
	SshHost         pulumi.StringPtrInput
	SshPort         pulumi.StringPtrInput
	SshPrivateKey   pulumi.StringPtrInput
	SshUser         pulumi.StringPtrInput
	Sshkeys         pulumi.StringPtrInput
	// Deprecated: Use `disk.storage` instead
	Storage pulumi.StringPtrInput
	// Deprecated: Use `disk.type` instead
	StorageType pulumi.StringPtrInput
	TargetNode  pulumi.StringPtrInput
	Vcpus       pulumi.IntPtrInput
	Vgas        QemuVMVgaArrayInput
	// Deprecated: Use `network.tag` instead
	Vlan pulumi.IntPtrInput
	Vmid pulumi.IntPtrInput
}

func (QemuVMState) ElementType() reflect.Type {
	return reflect.TypeOf((*qemuVMState)(nil)).Elem()
}

type qemuVMArgs struct {
	Agent    *int    `pulumi:"agent"`
	Balloon  *int    `pulumi:"balloon"`
	Bios     *string `pulumi:"bios"`
	Boot     *string `pulumi:"boot"`
	Bootdisk *string `pulumi:"bootdisk"`
	// Deprecated: Use `network.bridge` instead
	Bridge               *string `pulumi:"bridge"`
	CiWait               *int    `pulumi:"ciWait"`
	Cicustom             *string `pulumi:"cicustom"`
	Cipassword           *string `pulumi:"cipassword"`
	Ciuser               *string `pulumi:"ciuser"`
	Clone                *string `pulumi:"clone"`
	CloneWait            *int    `pulumi:"cloneWait"`
	Cores                *int    `pulumi:"cores"`
	Cpu                  *string `pulumi:"cpu"`
	DefineConnectionInfo *bool   `pulumi:"defineConnectionInfo"`
	Desc                 *string `pulumi:"desc"`
	// Deprecated: Use `disk.size` instead
	DiskGb                  *float64     `pulumi:"diskGb"`
	Disks                   []QemuVMDisk `pulumi:"disks"`
	ForceCreate             *bool        `pulumi:"forceCreate"`
	ForceRecreateOnChangeOf *string      `pulumi:"forceRecreateOnChangeOf"`
	FullClone               *bool        `pulumi:"fullClone"`
	Hastate                 *string      `pulumi:"hastate"`
	Hotplug                 *string      `pulumi:"hotplug"`
	Ipconfig0               *string      `pulumi:"ipconfig0"`
	Ipconfig1               *string      `pulumi:"ipconfig1"`
	Ipconfig2               *string      `pulumi:"ipconfig2"`
	Iso                     *string      `pulumi:"iso"`
	Kvm                     *bool        `pulumi:"kvm"`
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac        *string         `pulumi:"mac"`
	Memory     *int            `pulumi:"memory"`
	Name       *string         `pulumi:"name"`
	Nameserver *string         `pulumi:"nameserver"`
	Networks   []QemuVMNetwork `pulumi:"networks"`
	// Deprecated: Use `network` instead
	Nic             *string        `pulumi:"nic"`
	Numa            *bool          `pulumi:"numa"`
	Onboot          *bool          `pulumi:"onboot"`
	OsNetworkConfig *string        `pulumi:"osNetworkConfig"`
	OsType          *string        `pulumi:"osType"`
	Pool            *string        `pulumi:"pool"`
	Preprovision    *bool          `pulumi:"preprovision"`
	QemuOs          *string        `pulumi:"qemuOs"`
	Scsihw          *string        `pulumi:"scsihw"`
	Searchdomain    *string        `pulumi:"searchdomain"`
	Serials         []QemuVMSerial `pulumi:"serials"`
	Sockets         *int           `pulumi:"sockets"`
	SshForwardIp    *string        `pulumi:"sshForwardIp"`
	SshPrivateKey   *string        `pulumi:"sshPrivateKey"`
	SshUser         *string        `pulumi:"sshUser"`
	Sshkeys         *string        `pulumi:"sshkeys"`
	// Deprecated: Use `disk.storage` instead
	Storage *string `pulumi:"storage"`
	// Deprecated: Use `disk.type` instead
	StorageType *string     `pulumi:"storageType"`
	TargetNode  string      `pulumi:"targetNode"`
	Vcpus       *int        `pulumi:"vcpus"`
	Vgas        []QemuVMVga `pulumi:"vgas"`
	// Deprecated: Use `network.tag` instead
	Vlan *int `pulumi:"vlan"`
	Vmid *int `pulumi:"vmid"`
}

// The set of arguments for constructing a QemuVM resource.
type QemuVMArgs struct {
	Agent    pulumi.IntPtrInput
	Balloon  pulumi.IntPtrInput
	Bios     pulumi.StringPtrInput
	Boot     pulumi.StringPtrInput
	Bootdisk pulumi.StringPtrInput
	// Deprecated: Use `network.bridge` instead
	Bridge               pulumi.StringPtrInput
	CiWait               pulumi.IntPtrInput
	Cicustom             pulumi.StringPtrInput
	Cipassword           pulumi.StringPtrInput
	Ciuser               pulumi.StringPtrInput
	Clone                pulumi.StringPtrInput
	CloneWait            pulumi.IntPtrInput
	Cores                pulumi.IntPtrInput
	Cpu                  pulumi.StringPtrInput
	DefineConnectionInfo pulumi.BoolPtrInput
	Desc                 pulumi.StringPtrInput
	// Deprecated: Use `disk.size` instead
	DiskGb                  pulumi.Float64PtrInput
	Disks                   QemuVMDiskArrayInput
	ForceCreate             pulumi.BoolPtrInput
	ForceRecreateOnChangeOf pulumi.StringPtrInput
	FullClone               pulumi.BoolPtrInput
	Hastate                 pulumi.StringPtrInput
	Hotplug                 pulumi.StringPtrInput
	Ipconfig0               pulumi.StringPtrInput
	Ipconfig1               pulumi.StringPtrInput
	Ipconfig2               pulumi.StringPtrInput
	Iso                     pulumi.StringPtrInput
	Kvm                     pulumi.BoolPtrInput
	// Deprecated: Use `network.macaddr` to access the auto generated MAC address
	Mac        pulumi.StringPtrInput
	Memory     pulumi.IntPtrInput
	Name       pulumi.StringPtrInput
	Nameserver pulumi.StringPtrInput
	Networks   QemuVMNetworkArrayInput
	// Deprecated: Use `network` instead
	Nic             pulumi.StringPtrInput
	Numa            pulumi.BoolPtrInput
	Onboot          pulumi.BoolPtrInput
	OsNetworkConfig pulumi.StringPtrInput
	OsType          pulumi.StringPtrInput
	Pool            pulumi.StringPtrInput
	Preprovision    pulumi.BoolPtrInput
	QemuOs          pulumi.StringPtrInput
	Scsihw          pulumi.StringPtrInput
	Searchdomain    pulumi.StringPtrInput
	Serials         QemuVMSerialArrayInput
	Sockets         pulumi.IntPtrInput
	SshForwardIp    pulumi.StringPtrInput
	SshPrivateKey   pulumi.StringPtrInput
	SshUser         pulumi.StringPtrInput
	Sshkeys         pulumi.StringPtrInput
	// Deprecated: Use `disk.storage` instead
	Storage pulumi.StringPtrInput
	// Deprecated: Use `disk.type` instead
	StorageType pulumi.StringPtrInput
	TargetNode  pulumi.StringInput
	Vcpus       pulumi.IntPtrInput
	Vgas        QemuVMVgaArrayInput
	// Deprecated: Use `network.tag` instead
	Vlan pulumi.IntPtrInput
	Vmid pulumi.IntPtrInput
}

func (QemuVMArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*qemuVMArgs)(nil)).Elem()
}
